[tool.poetry]
name = "data_uploader"
version = "0.1.0"
description = "Monitors EPICS process variables representing images and scalars and handles them"
authors = ["Reinier van Mourik <reinier.vanmourik@tausystems.com>"]
readme = "README.md"
packages = [{include = "data_uploader"}]

[tool.poetry.dependencies]
python = "^3.10"

# For EPICS pvAccess and Channel Access
p4p = "^4.1.12"
numpy = "<2.0"  # p4p isn't compatible with numpy 2.0 but doesn't specify that in its pyproject.toml
nose2 = "^0.14.1"
pyepics = { git = "https://github.com/pyepics/pyepics.git", rev = "0b33db782dde77d89ee847bee4e6fc314bc3c30b" }

# For loading image devices and scalar variables
measurement_db = { path = "../../../measurement_db", develop = true }

# For uploading to image backend
requests = "^2.31.0"
tifffile = "^2024.2.12"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
hanging-threads = "^2.0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
