/*----- PROTECTED REGION ID(FLIRCamera.h) ENABLED START -----*/
//=============================================================================
//
// file :        FLIRCamera.h
//
// description : Include file for the FLIRCamera class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef FLIRCamera_H
#define FLIRCamera_H

#include <tango.h>
#include <Spinnaker.h>
#include <SpinGenApi/SpinnakerGenApi.h>
#include <SpinnakerDefs.h>

/*----- PROTECTED REGION END -----*/	//	FLIRCamera.h

/**
 *  FLIRCamera class description:
 *    
 */

namespace FLIRCamera_ns
{
/*----- PROTECTED REGION ID(FLIRCamera::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations
    class TriggerCallback : public Tango::CallBack {
    public:
        Tango::DeviceProxy TimingDevice;
        std::function<void(void)> callback;
        Tango::DevULong64 Timestamp;

        explicit TriggerCallback(const std::string& timingDeviceName) : callback(nullptr) {
            try {
                TimingDevice = Tango::DeviceProxy(timingDeviceName.c_str());
                TimingDevice.subscribe_event("Timestamp", Tango::DATA_READY_EVENT, this);
            } catch(Tango::DevFailed &e){
                Tango::Except::print_exception(e);
                throw;
            }
        }

        TriggerCallback(const TriggerCallback& rhs) {
            this->TimingDevice = rhs.TimingDevice;
            this->callback = rhs.callback;
            this->Timestamp = rhs.Timestamp;
        }

        TriggerCallback& operator=(const TriggerCallback& rhs) {
            this->TimingDevice = rhs.TimingDevice;
            this->callback = rhs.callback;
            this->Timestamp = rhs.Timestamp;
            return *this;
        }

        void SetCallback(const std::function<void(void)>& cb) {
            this->callback = cb;
        }

        void push_event(Tango::DataReadyEventData*) override {
            Tango::DevVarULong64Array* attr_val;
            TimingDevice.read_attribute("Timestamp") >> attr_val;
            Timestamp = (*attr_val)[0];
            delete attr_val;
            callback();
        }
    };

/*----- PROTECTED REGION END -----*/	//	FLIRCamera::Additional Class Declarations

class FLIRCamera : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(FLIRCamera::Data Members) ENABLED START -----*/

//	Add your own data members
        Spinnaker::CameraPtr SpinnakerCameraPtr;
        Spinnaker::ImagePtr ResultImagePtr;
        TriggerCallback TriggerCallbackInstance;
        std::string BasePath;
        std::string FolderPath;

/*----- PROTECTED REGION END -----*/	//	FLIRCamera::Data Members

//	Device property data members
public:
	//	serial:	
	string	serial;

	bool	mandatoryNotDefined;

//	Attribute data members
public:
	Tango::DevUShort	*attr_image_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	FLIRCamera(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	FLIRCamera(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	FLIRCamera(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~FLIRCamera() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();

	/*
	 *	Check if mandatory property has been set
	 */
	 void check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop);

//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : FLIRCamera::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute image related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Image max = 2048 x 1536
 */
	virtual void read_image(Tango::Attribute &attr);
	virtual bool is_image_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : FLIRCamera::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command BeginAcquisition related method
	 *	Description: 
	 *
	 */
	virtual void begin_acquisition();
	virtual bool is_BeginAcquisition_allowed(const CORBA::Any &any);
	/**
	 *	Command EndAcquisition related method
	 *	Description: 
	 *
	 */
	virtual void end_acquisition();
	virtual bool is_EndAcquisition_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : FLIRCamera::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(FLIRCamera::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes
void InitFLIRCamera();
void ConfigureFLIRCamera();
void GenerateImageOnTrigger();
void SetupImageDirectory();
bool FolderExists(const std::string&);
bool CreateFolder(const std::string&);

/*----- PROTECTED REGION END -----*/	//	FLIRCamera::Additional Method prototypes
};

/*----- PROTECTED REGION ID(FLIRCamera::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	FLIRCamera::Additional Classes Definitions

}	//	End of namespace

#endif   //	FLIRCamera_H
