/*----- PROTECTED REGION ID(FLIRCameraClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        FLIRCameraClass.h
//
// description : Include for the FLIRCamera root class.
//               This class is the singleton class for
//                the FLIRCamera device class.
//               It contains all properties and methods which the 
//               FLIRCamera requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef FLIRCameraClass_H
#define FLIRCameraClass_H

#include <tango.h>
#include <FLIRCamera.h>


/*----- PROTECTED REGION END -----*/	//	FLIRCameraClass.h


namespace FLIRCamera_ns
{
/*----- PROTECTED REGION ID(FLIRCameraClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	FLIRCameraClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute image class definition
class imageAttrib: public Tango::ImageAttr
{
public:
	imageAttrib():ImageAttr("image",
			Tango::DEV_USHORT, Tango::READ, 2048, 1536) {};
	~imageAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<FLIRCamera *>(dev))->read_image(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<FLIRCamera *>(dev))->is_image_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command BeginAcquisition class definition
class BeginAcquisitionClass : public Tango::Command
{
public:
	BeginAcquisitionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	BeginAcquisitionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~BeginAcquisitionClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<FLIRCamera *>(dev))->is_BeginAcquisition_allowed(any);}
};

//	Command EndAcquisition class definition
class EndAcquisitionClass : public Tango::Command
{
public:
	EndAcquisitionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	EndAcquisitionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~EndAcquisitionClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<FLIRCamera *>(dev))->is_EndAcquisition_allowed(any);}
};


/**
 *	The FLIRCameraClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  FLIRCameraClass : public Tango::DeviceClass
#else
class FLIRCameraClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(FLIRCameraClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCameraClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static FLIRCameraClass *init(const char *);
		static FLIRCameraClass *instance();
		~FLIRCameraClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		FLIRCameraClass(string &);
		static FLIRCameraClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	FLIRCamera_H
