/*----- PROTECTED REGION ID(FLIRCameraStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        FLIRCameraStateMachine.cpp
//
// description : State machine file for the FLIRCamera class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <FLIRCamera.h>

/*----- PROTECTED REGION END -----*/	//	FLIRCamera::FLIRCameraStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  
//  OFF      |  
//  RUNNING  |  
//  FAULT    |  


namespace FLIRCamera_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::is_image_allowed()
 *	Description : Execution allowed for image attribute
 */
//--------------------------------------------------------
bool FLIRCamera::is_image_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for image attribute in read access.
	/*----- PROTECTED REGION ID(FLIRCamera::imageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::imageStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::is_BeginAcquisition_allowed()
 *	Description : Execution allowed for BeginAcquisition attribute
 */
//--------------------------------------------------------
bool FLIRCamera::is_BeginAcquisition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::RUNNING ||
		get_state()==Tango::FAULT)
	{
	/*----- PROTECTED REGION ID(FLIRCamera::BeginAcquisitionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::BeginAcquisitionStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::is_EndAcquisition_allowed()
 *	Description : Execution allowed for EndAcquisition attribute
 */
//--------------------------------------------------------
bool FLIRCamera::is_EndAcquisition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(FLIRCamera::EndAcquisitionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::EndAcquisitionStateAllowed
		return false;
	}
	return true;
}


/*----- PROTECTED REGION ID(FLIRCamera::FLIRCameraStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	FLIRCamera::FLIRCameraStateAllowed.AdditionalMethods

}	//	End of namespace
