/*----- PROTECTED REGION ID(FLIRCamera.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        FLIRCamera.cpp
//
// description : C++ source for the FLIRCamera class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               FLIRCamera are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <FLIRCamera.h>
#include <FLIRCameraClass.h>
#include <string>
#include <filesystem>
#include <boost/format.hpp>
#include <boost/date_time.hpp>

/*----- PROTECTED REGION END -----*/	//	FLIRCamera.cpp

/**
 *  FLIRCamera class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name      |  Method name
//================================================================
//  State             |  Inherited (no method)
//  Status            |  Inherited (no method)
//  BeginAcquisition  |  begin_acquisition
//  EndAcquisition    |  end_acquisition
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//  image  |  Tango::DevUShort	Image  ( max = 2048 x 1536)
//================================================================

namespace FLIRCamera_ns
{
/*----- PROTECTED REGION ID(FLIRCamera::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	FLIRCamera::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::FLIRCamera()
 *	Description : Constructors for a Tango device
 *                implementing the classFLIRCamera
 */
//--------------------------------------------------------
FLIRCamera::FLIRCamera(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str()), TriggerCallbackInstance("ut3/timing/tdu")
{
	/*----- PROTECTED REGION ID(FLIRCamera::constructor_1) ENABLED START -----*/
    SpinnakerCameraPtr = nullptr;
    ResultImagePtr = nullptr;
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::constructor_1
}
//--------------------------------------------------------
FLIRCamera::FLIRCamera(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s), TriggerCallbackInstance("ut3/timing/tdu")
{
	/*----- PROTECTED REGION ID(FLIRCamera::constructor_2) ENABLED START -----*/
    SpinnakerCameraPtr = nullptr;
    ResultImagePtr = nullptr;
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::constructor_2
}
//--------------------------------------------------------
FLIRCamera::FLIRCamera(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d), TriggerCallbackInstance("ut3/timing/tdu")
{
	/*----- PROTECTED REGION ID(FLIRCamera::constructor_3) ENABLED START -----*/
    SpinnakerCameraPtr = nullptr;
    ResultImagePtr = nullptr;
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void FLIRCamera::delete_device()
{
	DEBUG_STREAM << "FLIRCamera::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(FLIRCamera::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::delete_device
	delete[] attr_image_read;
}

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void FLIRCamera::init_device()
{
	DEBUG_STREAM << "FLIRCamera::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(FLIRCamera::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_image_read = new Tango::DevUShort[2048*1536];
	//	No longer if mandatory property not set. 
	if (mandatoryNotDefined)
		return;

	/*----- PROTECTED REGION ID(FLIRCamera::init_device) ENABLED START -----*/
    set_data_ready_event("image", true);

    SetupImageDirectory();
	
	//	Initialize device
    InitFLIRCamera();
    ConfigureFLIRCamera();

    // Set callback function to GenerateImageOnTrigger
    TriggerCallbackInstance.SetCallback(std::bind(&FLIRCamera::GenerateImageOnTrigger, this));

	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::init_device
}

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void FLIRCamera::get_device_property()
{
	/*----- PROTECTED REGION ID(FLIRCamera::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::get_device_property_before

	mandatoryNotDefined = false;

	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("serial"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on FLIRCameraClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		FLIRCameraClass	*ds_class =
			(static_cast<FLIRCameraClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize serial from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  serial;
		else {
			//	Try to initialize serial from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  serial;
		}
		//	And try to extract serial value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  serial;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

	}

	/*----- PROTECTED REGION ID(FLIRCamera::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::get_device_property_after
}
//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::check_mandatory_property()
 *	Description : For mandatory properties check if defined in database.
 */
//--------------------------------------------------------
void FLIRCamera::check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop)
{
	//	Check if all properties are empty
	if (class_prop.is_empty() && dev_prop.is_empty())
	{
		TangoSys_OMemStream	tms;
		tms << endl <<"Property \'" << dev_prop.name;
		if (Tango::Util::instance()->_UseDb==true)
			tms << "\' is mandatory but not defined in database";
		else
			tms << "\' is mandatory but cannot be defined without database";
		append_status(tms.str());
		mandatoryNotDefined = true;
		/*----- PROTECTED REGION ID(FLIRCamera::check_mandatory_property) ENABLED START -----*/
		cerr << tms.str() << " for " << device_name << endl;
		
		/*----- PROTECTED REGION END -----*/	//	FLIRCamera::check_mandatory_property
	}
}


//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void FLIRCamera::always_executed_hook()
{
	DEBUG_STREAM << "FLIRCamera::always_executed_hook()  " << device_name << endl;
	if (mandatoryNotDefined)
	{
		Tango::Except::throw_exception(
					(const char *)"PROPERTY_NOT_SET",
					get_status().c_str(),
					(const char *)"FLIRCamera::always_executed_hook()");
	}
	/*----- PROTECTED REGION ID(FLIRCamera::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void FLIRCamera::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "FLIRCamera::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(FLIRCamera::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute image related method
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Image max = 2048 x 1536
 */
//--------------------------------------------------------
void FLIRCamera::read_image(Tango::Attribute &attr)
{
	DEBUG_STREAM << "FLIRCamera::read_image(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(FLIRCamera::read_image) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_image_read, 2048, 1536);
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::read_image
}

//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void FLIRCamera::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(FLIRCamera::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command BeginAcquisition related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void FLIRCamera::begin_acquisition()
{
	DEBUG_STREAM << "FLIRCamera::BeginAcquisition()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(FLIRCamera::begin_acquisition) ENABLED START -----*/
	
	//	Add your own code
    try {
        // Setting up the trigger callback
        set_state(Tango::RUNNING);
        SpinnakerCameraPtr->BeginAcquisition();
        std::cout << "Begin acquisition on " << device_name << std::endl;
    } catch (Spinnaker::Exception& e) {
        std::cout << "Exception caught on starting acquisition:" << device_name << ": " << e.what() << std::endl;
    }
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::begin_acquisition
}
//--------------------------------------------------------
/**
 *	Command EndAcquisition related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void FLIRCamera::end_acquisition()
{
	DEBUG_STREAM << "FLIRCamera::EndAcquisition()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(FLIRCamera::end_acquisition) ENABLED START -----*/
	
	//	Add your own code
    try {
        // Setting up the trigger callback
        SpinnakerCameraPtr->EndAcquisition();
        set_state(Tango::ON);
        std::cout << "End acquisition on " << device_name << std::endl;
    } catch (Spinnaker::Exception& e) {
        std::cout << "Exception caught on starting acquisition:" << device_name << ": " << e.what() << std::endl;
    }
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::end_acquisition
}
//--------------------------------------------------------
/**
 *	Method      : FLIRCamera::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void FLIRCamera::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(FLIRCamera::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	FLIRCamera::add_dynamic_commands
}

/*----- PROTECTED REGION ID(FLIRCamera::namespace_ending) ENABLED START -----*/

//	Additional Methods
void FLIRCamera::InitFLIRCamera() {
    try {
        Spinnaker::CameraList camList = Spinnaker::System::GetInstance()->GetCameras();
        bool foundDevice = false;
        for (int i = 0; i < camList.GetSize(); i++) {
            Spinnaker::CameraPtr pCam = camList.GetByIndex(i);
            if (IsReadable(pCam->TLDevice.DeviceSerialNumber)) {
                if (pCam->TLDevice.DeviceSerialNumber.GetValue() == serial.c_str()) {
                    foundDevice = true;
                    SpinnakerCameraPtr = pCam;
                }
            }
        }
        if (foundDevice) {
            SpinnakerCameraPtr->Init();
            set_state(Tango::ON);
            std::cout << "Found device " << device_name << "." << std::endl;
        } else {
            set_state(Tango::OFF);
            std::cout << "Device " << device_name << " not found!" << std::endl;
        }

        camList.Clear();
    } catch (Spinnaker::Exception& e) {
        std::cout << "Exception caught on initializing " << device_name << ": " << e.what() << std::endl;
    }
}

void FLIRCamera::ConfigureFLIRCamera() {
    try {
        std::cout << "Set acquisition mode to continuous." << std::endl;
        SpinnakerCameraPtr->AcquisitionMode.SetValue(Spinnaker::AcquisitionModeEnums::AcquisitionMode_Continuous);
        std::cout << "Set device link throughput limit to: " << SpinnakerCameraPtr->DeviceLinkThroughputLimit.GetMin() * 10 << "bps" << std::endl;
        SpinnakerCameraPtr->DeviceLinkThroughputLimit.SetValue(SpinnakerCameraPtr->DeviceLinkThroughputLimit.GetMin() * 10);
        std::cout << "Set exposure mode to timed." << std::endl;
        SpinnakerCameraPtr->ExposureMode.SetValue(Spinnaker::ExposureModeEnums::ExposureMode_Timed);
        std::cout << "Set exposure time to 25 ms." << std::endl;
        SpinnakerCameraPtr->ExposureAuto.SetValue(Spinnaker::ExposureAutoEnums::ExposureAuto_Off);
        SpinnakerCameraPtr->ExposureTime.SetValue(2.5E4);
        std::cout << "Set gain to 0." << std::endl;
        SpinnakerCameraPtr->GainAuto.SetValue(Spinnaker::GainAutoEnums::GainAuto_Off);
        SpinnakerCameraPtr->Gain.SetValue(0);
        std::cout << "Set image size to maximum." << std::endl;
        SpinnakerCameraPtr->Width.SetValue(SpinnakerCameraPtr->Width.GetMax());
        SpinnakerCameraPtr->Height.SetValue(SpinnakerCameraPtr->Height.GetMax());
        std::cout << "Set pixel format to Mono16." << std::endl;
        SpinnakerCameraPtr->PixelFormat.SetValue(Spinnaker::PixelFormatEnums::PixelFormat_Mono16);
        std::cout << "Set trigger delay to minimum." << std::endl;
        SpinnakerCameraPtr->TriggerDelay.SetValue(SpinnakerCameraPtr->TriggerDelay.GetMin());

        // Set shot mode
        std::cout << "Set trigger mode to on." << std::endl;
        SpinnakerCameraPtr->TriggerMode.SetValue(Spinnaker::TriggerModeEnums::TriggerMode_On);
        std::cout << "Set trigger source to Line0." << std::endl;
        SpinnakerCameraPtr->TriggerSource.SetValue(Spinnaker::TriggerSourceEnums::TriggerSource_Line0);
        std::cout << "Set trigger selector to frame start." << std::endl;
        SpinnakerCameraPtr->TriggerSelector.SetValue(Spinnaker::TriggerSelectorEnums::TriggerSelector_FrameStart);
        std::cout << "Set trigger activation to rising edge." << std::endl;
        SpinnakerCameraPtr->TriggerActivation.SetValue(Spinnaker::TriggerActivationEnums::TriggerActivation_RisingEdge);
    } catch (Spinnaker::Exception& e) {
        std::cout << "Exception caught on configuring " << device_name << ": " << e.what() << std::endl;
        set_state(Tango::FAULT);
    }
}

void FLIRCamera::GenerateImageOnTrigger() {
	if (get_state() == Tango::RUNNING) {
		ResultImagePtr = SpinnakerCameraPtr->GetNextImage();
		if (ResultImagePtr->IsIncomplete()) {
			std::cout << device_name << " incomplete with err: " << ResultImagePtr->GetImageStatus() << std::endl;
			ResultImagePtr->Release();
		} else {
			const std::string filename = boost::str(boost::format("%1%/ts_%2%.tiff") % FolderPath % TriggerCallbackInstance.Timestamp);
			ResultImagePtr->Save(filename.c_str());
			push_data_ready_event("image");
			std::cout << "Saved " << filename << "\n";
			if (ResultImagePtr.IsValid()) ResultImagePtr->Release();
		}
	} else {
		std::cout << device_name << " DAQ not started.\n";
		return;
	}
}

bool FLIRCamera::FolderExists(const std::string& folderPath) {
    return std::filesystem::exists(folderPath) && std::filesystem::is_directory(folderPath);
}

bool FLIRCamera::CreateFolder(const std::string& folderPath) {
    try {
        std::filesystem::create_directories(folderPath);
        std::cout << "Folder created successfully: " << folderPath << std::endl;
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error creating folder: " << folderPath << " - " << e.what() << std::endl;
        return false;
    }
}

void FLIRCamera::SetupImageDirectory() {
    // BasePath = "/home/ut3daq/TauPool-UT3/CommissionData";
    BasePath = "/home/ut3daq/TestDir";
    auto iso_date = boost::gregorian::to_iso_extended_string(boost::gregorian::day_clock::local_day());
    FolderPath = boost::str(boost::format("%1%/%2%/%3%") % BasePath % iso_date % device_name);

    if (!FolderExists(FolderPath)) {
        std::cout << "Folder " << FolderPath << " doesn't exist. Creating..."  << std::endl;
        CreateFolder(FolderPath);
    } else {
        std::cout << "Folder already exists: " << FolderPath << std::endl;
    }
}

/*----- PROTECTED REGION END -----*/	//	FLIRCamera::namespace_ending
} //	namespace
